[project]
name = "drip"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pex>=2.69.1",
    "pyinstaller>=6.16.0",
    "toml>=0.10.2",
    "tomli-w>=1.2.0",
]
